"""Codegen — JSON model artifact -> deployable Trader file.

Reads ``round5/ml/artifacts/<FAMILY>_{ridge,signal}.json`` and emits
``round5/strats/strat_ml_<FAMILY>.py`` that:
  - Embeds the artifact inline as a Python dict literal (Lambda forbids
    arbitrary file IO at runtime).
  - Maintains per-product mid/microprice_dev/trade-flow ring buffers in
    ``traderData`` so features can be computed tick-by-tick.
  - On each tick: computes the whitelist features, normalises with the
    artifact's stored mean/std, dot-products with coefs to get the
    predicted edge, applies ``live_haircut``, and crosses the spread when
    ``|edge| > 0.5 * spread + buffer``.

Both ``kind: ml_ridge`` and ``kind: simple_signal`` artifacts produce the
same trader shape — the simple-signal case is just a 1-feature model on a
single product. Codegen picks the right template branch from ``MODEL["kind"]``.

Usage::

    .venv/Scripts/python.exe round5/ml/codegen.py \\
        --artifact round5/ml/artifacts/PEBBLES_signal.json
    .venv/Scripts/python.exe round5/ml/codegen.py --all
"""
from __future__ import annotations

import argparse
import json
import pprint
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from round5 import research_lib as rl  # noqa: E402

DEFAULT_ARTIFACT_DIR = ROOT / "round5" / "ml" / "artifacts"
DEFAULT_OUT_DIR = ROOT / "round5" / "strats"


_TEMPLATE = '''"""Auto-generated by round5/ml/codegen.py — do NOT edit by hand.

Family : {family}
Kind   : {kind}
Source : {source_artifact}
"""
try:
    from datamodel import OrderDepth, TradingState, Order, Symbol, Listing, Observation, Trade, ProsperityEncoder
except ImportError:
    from prosperity4bt.datamodel import OrderDepth, TradingState, Order, Symbol, Listing, Observation, Trade, ProsperityEncoder
from typing import Any, Dict, List, Tuple
import json
import math


class Logger:
    def __init__(self) -> None:
        self.logs = ""
        self.max_log_length = 3750

    def print(self, *objects: Any, sep: str = " ", end: str = "\\n") -> None:
        self.logs += sep.join(map(str, objects)) + end

    def flush(self, state, orders, conversions, trader_data):
        base = len(self.to_json([self.compress_state(state, ""), self.compress_orders(orders), conversions, "", ""]))
        max_item = (self.max_log_length - base) // 3
        print(self.to_json([
            self.compress_state(state, self.truncate(state.traderData, max_item)),
            self.compress_orders(orders), conversions,
            self.truncate(trader_data, max_item), self.truncate(self.logs, max_item),
        ]))
        self.logs = ""

    def compress_state(self, state, td):
        return [state.timestamp, td, [[l.symbol, l.product, l.denomination] for l in state.listings.values()],
                {{s: [od.buy_orders, od.sell_orders] for s, od in state.order_depths.items()}},
                [[t.symbol, t.price, t.quantity, t.buyer, t.seller, t.timestamp] for arr in state.own_trades.values() for t in arr],
                [[t.symbol, t.price, t.quantity, t.buyer, t.seller, t.timestamp] for arr in state.market_trades.values() for t in arr],
                state.position, [state.observations.plainValueObservations,
                                 {{p: [o.bidPrice, o.askPrice, o.transportFees, o.exportTariff, o.importTariff,
                                      getattr(o, "sugarPrice", 0), getattr(o, "sunlightIndex", 0)]
                                  for p, o in state.observations.conversionObservations.items()}}]]

    def compress_orders(self, orders):
        return [[o.symbol, o.price, o.quantity] for arr in orders.values() for o in arr]

    def to_json(self, v): return json.dumps(v, cls=ProsperityEncoder, separators=(",", ":"))

    def truncate(self, v, n):
        lo, hi, out = 0, min(len(v), n), ""
        while lo <= hi:
            mid = (lo + hi) // 2
            cand = v[:mid] + ("..." if mid < len(v) else "")
            if len(json.dumps(cand)) <= n:
                out, lo = cand, mid + 1
            else:
                hi = mid - 1
        return out


logger = Logger()


# ============================================================================
# Embedded model artifact (do not edit — regenerate via codegen.py)
# ============================================================================

MODEL: Dict[str, Any] = {model_json}


# ============================================================================
# Constants
# ============================================================================

POSITION_LIMIT = 10
BASE_QTY = 3                    # aggressive crossing size when |edge| > threshold
MID_BUFFER_LEN = 520            # std_500 needs 500 + small headroom
MPDEV_BUFFER_LEN = 8            # microprice_dev_lag5 + headroom
RET1_BUFFER_LEN = 4             # ret_1_lag1 needs 2-3
TRADEFLOW_BUFFER_LEN = 25       # signed_flow_20 + headroom
WARMUP_TICKS = 60               # need at least this many mids for ret_10/std_50

FAMILY = MODEL["family"]
KIND = MODEL["kind"]
HORIZON = int(MODEL["horizon"])
LIVE_HAIRCUT = float(MODEL["live_haircut"])
ENTRY_BUFFER = float(MODEL["entry_buffer"])
FEATURES: List[str] = list(MODEL.get("features") or [MODEL.get("signal")])
FEATURE_MEANS: List[float] = list(MODEL.get("feature_means", []))
FEATURE_STDS: List[float] = list(MODEL.get("feature_stds", []))
COEFS: List[float] = list(MODEL.get("coefs", []))
INTERCEPT: float = float(MODEL.get("intercept", 0.0))

if KIND == "simple_signal":
    PRODUCT_TARGETS: List[str] = [MODEL["product"]]
else:
    PRODUCT_TARGETS = list({family_products!r})
FAMILY_PRODUCTS: List[str] = list({family_products!r})


# ============================================================================
# Per-tick feature computation
# ============================================================================

def _ob_imbalances(od: OrderDepth) -> Tuple[float, float]:
    """obi_l1 (top-of-book) and obi_l3 (3-level) imbalance."""
    bids = od.buy_orders
    asks = od.sell_orders
    if not bids or not asks:
        return 0.0, 0.0
    bid_levels = sorted(bids.items(), key=lambda kv: -kv[0])[:3]
    ask_levels = sorted(asks.items(), key=lambda kv: kv[0])[:3]
    b1 = float(bid_levels[0][1]) if bid_levels else 0.0
    a1 = float(-ask_levels[0][1]) if ask_levels else 0.0
    bT = sum(float(v) for _, v in bid_levels)
    aT = sum(float(-v) for _, v in ask_levels)
    obi_l1 = (b1 - a1) / (b1 + a1) if (b1 + a1) > 0 else 0.0
    obi_l3 = (bT - aT) / (bT + aT) if (bT + aT) > 0 else 0.0
    return obi_l1, obi_l3


def _microprice_dev(od: OrderDepth, mid: float) -> float:
    bids = od.buy_orders
    asks = od.sell_orders
    if not bids or not asks:
        return 0.0
    best_bid = max(bids.keys())
    best_ask = min(asks.keys())
    b1 = float(bids[best_bid])
    a1 = float(-asks[best_ask])
    if (b1 + a1) <= 0:
        return 0.0
    micro = (best_bid * a1 + best_ask * b1) / (b1 + a1)
    return micro - mid


def _running_std(seq: List[float]) -> float:
    n = len(seq)
    if n < 2:
        return 0.0
    mu = sum(seq) / n
    var = sum((x - mu) ** 2 for x in seq) / (n - 1)
    return var ** 0.5


def compute_features(
    sym: str,
    od: OrderDepth,
    bid: int,
    ask: int,
    mid: float,
    mids_hist: Dict[str, List[float]],
    mpdev_hist: Dict[str, List[float]],
    ret1_hist: Dict[str, List[float]],
    flow_hist: Dict[str, List[float]],
    market_trades_now: List,
    fam_mpdev_lag5_now: float,
) -> Dict[str, float]:
    """Compute the 10-feature whitelist (or a subset matching MODEL features)."""
    feats: Dict[str, float] = {{}}
    obi_l1, obi_l3 = _ob_imbalances(od)
    mp_dev = _microprice_dev(od, mid)
    spread = float(ask - bid)
    spread_bps = (1e4 * spread / mid) if mid > 0 else 0.0

    mids = mids_hist.get(sym, [])
    if len(mids) >= 11:
        ret_10 = mid - mids[-11]
    else:
        ret_10 = 0.0

    r1 = ret1_hist.get(sym, [])
    ret_1_lag1 = r1[-2] if len(r1) >= 2 else 0.0

    if len(mids) >= 50:
        std_50 = _running_std(mids[-50:])
    else:
        std_50 = 0.0
    if len(mids) >= 50:
        std_500 = _running_std(mids[-500:]) if len(mids) >= 50 else 0.0
    else:
        std_500 = 0.0

    mpd_seq = mpdev_hist.get(sym, [])
    mp_dev_lag5 = mpd_seq[-6] if len(mpd_seq) >= 6 else 0.0

    flow = flow_hist.get(sym, [])
    if len(flow) >= 1:
        signed_flow_20 = float(sum(flow[-20:]))
    else:
        signed_flow_20 = 0.0
    # Update flow buffer with this tick's signed flow.
    new_flow_pts: float = 0.0
    for t in market_trades_now:
        try:
            price = float(t.price)
            qty = float(t.quantity)
        except Exception:
            continue
        sgn = 1.0 if price > mid else (-1.0 if price < mid else 0.0)
        new_flow_pts += sgn * qty
    flow.append(new_flow_pts)
    if len(flow) > TRADEFLOW_BUFFER_LEN:
        flow = flow[-TRADEFLOW_BUFFER_LEN:]
    flow_hist[sym] = flow

    feats["obi_l1"] = obi_l1
    feats["obi_l3"] = obi_l3
    feats["microprice_dev"] = mp_dev
    feats["spread_bps"] = spread_bps
    feats["ret_10"] = ret_10
    feats["ret_1_lag1"] = ret_1_lag1
    feats["signed_flow_20"] = signed_flow_20
    feats["std_500"] = std_500
    feats["std_50"] = std_50
    feats["microprice_dev_lag5"] = mp_dev_lag5
    feats["fam_mean_microprice_dev_lag5"] = fam_mpdev_lag5_now

    # Signal aliases for simple-signal kind:
    feats["momentum_10"] = ret_10
    feats["neg_spread"] = -spread

    # Live z-score of mid (50): only computable once mids has 50 entries.
    if len(mids) >= 50:
        recent = mids[-50:]
        mu = sum(recent) / 50
        sd = _running_std(recent)
        if sd > 0:
            feats["neg_zscore_mid_50"] = -(mid - mu) / sd
            feats["neg_zscore_vwap_50"] = feats["neg_zscore_mid_50"]  # vwap not tracked live
        else:
            feats["neg_zscore_mid_50"] = 0.0
            feats["neg_zscore_vwap_50"] = 0.0
    else:
        feats["neg_zscore_mid_50"] = 0.0
        feats["neg_zscore_vwap_50"] = 0.0

    feats["trade_imbalance"] = signed_flow_20  # alias used by simple-signal naming
    return feats


def predict_edge(features: Dict[str, float]) -> float:
    """Standardise + dot product."""
    edge = INTERCEPT
    for i, f in enumerate(FEATURES):
        x = float(features.get(f, 0.0))
        mu = FEATURE_MEANS[i] if i < len(FEATURE_MEANS) else 0.0
        sd = FEATURE_STDS[i] if i < len(FEATURE_STDS) else 1.0
        if sd == 0:
            sd = 1.0
        edge += COEFS[i] * (x - mu) / sd
    return edge


# ============================================================================
# Trader
# ============================================================================


class Trader:
    def run(self, state: TradingState) -> Tuple[Dict[Symbol, List[Order]], int, str]:
        result: Dict[Symbol, List[Order]] = {{}}
        conversions = 0
        td = json.loads(state.traderData) if state.traderData else {{}}

        mids_hist: Dict[str, List[float]] = td.get("mids", {{}})
        mpdev_hist: Dict[str, List[float]] = td.get("mpdev", {{}})
        ret1_hist: Dict[str, List[float]] = td.get("ret1", {{}})
        flow_hist: Dict[str, List[float]] = td.get("flow", {{}})

        bb: Dict[str, int] = {{}}
        ba: Dict[str, int] = {{}}
        mids: Dict[str, float] = {{}}
        for sym in FAMILY_PRODUCTS:
            if sym not in state.order_depths:
                continue
            od = state.order_depths[sym]
            if not od.buy_orders or not od.sell_orders:
                continue
            bb[sym] = max(od.buy_orders.keys())
            ba[sym] = min(od.sell_orders.keys())
            mids[sym] = (bb[sym] + ba[sym]) / 2.0

        # Update per-symbol mid + microprice_dev + ret_1 buffers BEFORE feature compute.
        for sym in FAMILY_PRODUCTS:
            if sym not in mids:
                continue
            mid = mids[sym]
            hist = mids_hist.get(sym, [])
            if hist:
                ret_1 = mid - hist[-1]
            else:
                ret_1 = 0.0
            hist.append(mid)
            if len(hist) > MID_BUFFER_LEN:
                hist = hist[-MID_BUFFER_LEN:]
            mids_hist[sym] = hist

            r1seq = ret1_hist.get(sym, [])
            r1seq.append(ret_1)
            if len(r1seq) > RET1_BUFFER_LEN:
                r1seq = r1seq[-RET1_BUFFER_LEN:]
            ret1_hist[sym] = r1seq

            mp_dev_now = _microprice_dev(state.order_depths[sym], mid)
            mp_seq = mpdev_hist.get(sym, [])
            mp_seq.append(mp_dev_now)
            if len(mp_seq) > MPDEV_BUFFER_LEN:
                mp_seq = mp_seq[-MPDEV_BUFFER_LEN:]
            mpdev_hist[sym] = mp_seq

        # Family-mean microprice_dev_lag5 (one scalar per tick across the family).
        lag5_vals = []
        for sym in FAMILY_PRODUCTS:
            seq = mpdev_hist.get(sym, [])
            if len(seq) >= 6:
                lag5_vals.append(seq[-6])
        fam_mpdev_lag5 = sum(lag5_vals) / len(lag5_vals) if lag5_vals else 0.0

        for sym in PRODUCT_TARGETS:
            if sym not in mids:
                continue
            mids_local = mids_hist.get(sym, [])
            if len(mids_local) < WARMUP_TICKS:
                continue

            market_trades = state.market_trades.get(sym, [])
            feats = compute_features(
                sym, state.order_depths[sym], bb[sym], ba[sym], mids[sym],
                mids_hist, mpdev_hist, ret1_hist, flow_hist,
                market_trades, fam_mpdev_lag5,
            )
            edge_raw = predict_edge(feats)
            edge = edge_raw * LIVE_HAIRCUT

            spread = float(ba[sym] - bb[sym])
            half_sp = 0.5 * spread
            threshold = half_sp + ENTRY_BUFFER

            pos = state.position.get(sym, 0)
            orders: List[Order] = []
            if edge > threshold and pos < POSITION_LIMIT:
                qty = min(BASE_QTY, POSITION_LIMIT - pos)
                if qty > 0:
                    orders.append(Order(sym, ba[sym], +qty))
            elif edge < -threshold and pos > -POSITION_LIMIT:
                qty = min(BASE_QTY, POSITION_LIMIT + pos)
                if qty > 0:
                    orders.append(Order(sym, bb[sym], -qty))

            if orders:
                result[sym] = orders

        td["mids"] = mids_hist
        td["mpdev"] = mpdev_hist
        td["ret1"] = ret1_hist
        td["flow"] = flow_hist
        s = json.dumps(td)
        logger.flush(state, result, conversions, s)
        return result, conversions, s
'''


def emit_trader(artifact_path: Path, out_dir: Path) -> Path:
    artifact = json.loads(artifact_path.read_text(encoding="utf-8"))
    family = artifact["family"]
    fam_prods = list(rl.FAMILIES[family])

    # Embed as a Python literal (json.dumps would emit `true/false/null` which Python rejects).
    model_literal = pprint.pformat(artifact, indent=2, width=120, sort_dicts=False)

    rendered = _TEMPLATE.format(
        family=family,
        kind=artifact["kind"],
        source_artifact=artifact_path.name,
        model_json=model_literal,
        family_products=fam_prods,
    )
    out_path = out_dir / f"strat_ml_{family.lower()}.py"
    out_path.write_text(rendered, encoding="utf-8")
    return out_path


def emit_all(artifact_dir: Path, out_dir: Path) -> list[Path]:
    out: list[Path] = []
    for f in sorted(artifact_dir.glob("*_ridge.json")) + sorted(artifact_dir.glob("*_signal.json")):
        out.append(emit_trader(f, out_dir))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Trader files from ML artifacts.")
    ap.add_argument("--artifact", type=Path, default=None)
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--artifact-dir", type=Path, default=DEFAULT_ARTIFACT_DIR)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT_DIR)
    args = ap.parse_args()

    if args.all:
        paths = emit_all(args.artifact_dir, args.out)
    else:
        if args.artifact is None:
            print("provide --artifact <path> or --all", file=sys.stderr)
            return 2
        paths = [emit_trader(args.artifact, args.out)]

    for p in paths:
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
