"""Combine multiple model artifacts into one submission trader.

Reads N artifact JSONs (typically the surviving signal baselines) and emits a
single ``round5/strats/strat_ml_combined.py`` that:
  - Embeds all N models inline as a Python list of dicts.
  - Maintains per-product mid history + light microstructure buffers needed
    to compute every model's feature(s).
  - Each tick: for every model, compute its predicted edge on its target
    product(s) and place a crossing order if |edge| > 0.5*spread + buffer.

Models do NOT interact — each one drives independent positions on its own
product(s). The combined trader is exactly the disjoint union of the per-family
ones (per memory `feedback_pair_disjoint_legs`: no symbol owned by two models).
A pre-flight check enforces that.

Usage::

    .venv/Scripts/python.exe round5/ml/combine.py \\
        round5/ml/artifacts/MICROCHIP_signal.json \\
        round5/ml/artifacts/GALAXY_SOUNDS_signal.json \\
        round5/ml/artifacts/PANEL_signal.json \\
        round5/ml/artifacts/UV_VISOR_signal.json
"""
from __future__ import annotations

import argparse
import json
import pprint
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from round5 import research_lib as rl  # noqa: E402

DEFAULT_OUT = ROOT / "round5" / "strats" / "strat_ml_combined.py"


_TEMPLATE = '''"""Auto-generated by round5/ml/combine.py — do NOT edit by hand.

Combined trader: {n_models} models from {sources}.

Targets (disjoint):
{targets_list}
"""
try:
    from datamodel import OrderDepth, TradingState, Order, Symbol, Listing, Observation, Trade, ProsperityEncoder
except ImportError:
    from prosperity4bt.datamodel import OrderDepth, TradingState, Order, Symbol, Listing, Observation, Trade, ProsperityEncoder
from typing import Any, Dict, List, Tuple
import json
import math


class Logger:
    def __init__(self) -> None:
        self.logs = ""
        self.max_log_length = 3750

    def print(self, *objects: Any, sep: str = " ", end: str = "\\n") -> None:
        self.logs += sep.join(map(str, objects)) + end

    def flush(self, state, orders, conversions, trader_data):
        base = len(self.to_json([self.compress_state(state, ""), self.compress_orders(orders), conversions, "", ""]))
        max_item = (self.max_log_length - base) // 3
        print(self.to_json([
            self.compress_state(state, self.truncate(state.traderData, max_item)),
            self.compress_orders(orders), conversions,
            self.truncate(trader_data, max_item), self.truncate(self.logs, max_item),
        ]))
        self.logs = ""

    def compress_state(self, state, td):
        return [state.timestamp, td, [[l.symbol, l.product, l.denomination] for l in state.listings.values()],
                {{s: [od.buy_orders, od.sell_orders] for s, od in state.order_depths.items()}},
                [[t.symbol, t.price, t.quantity, t.buyer, t.seller, t.timestamp] for arr in state.own_trades.values() for t in arr],
                [[t.symbol, t.price, t.quantity, t.buyer, t.seller, t.timestamp] for arr in state.market_trades.values() for t in arr],
                state.position, [state.observations.plainValueObservations,
                                 {{p: [o.bidPrice, o.askPrice, o.transportFees, o.exportTariff, o.importTariff,
                                      getattr(o, "sugarPrice", 0), getattr(o, "sunlightIndex", 0)]
                                  for p, o in state.observations.conversionObservations.items()}}]]

    def compress_orders(self, orders):
        return [[o.symbol, o.price, o.quantity] for arr in orders.values() for o in arr]

    def to_json(self, v): return json.dumps(v, cls=ProsperityEncoder, separators=(",", ":"))

    def truncate(self, v, n):
        lo, hi, out = 0, min(len(v), n), ""
        while lo <= hi:
            mid = (lo + hi) // 2
            cand = v[:mid] + ("..." if mid < len(v) else "")
            if len(json.dumps(cand)) <= n:
                out, lo = cand, mid + 1
            else:
                hi = mid - 1
        return out


logger = Logger()


# ============================================================================
# Embedded models (do not edit — regenerate via combine.py)
# ============================================================================

MODELS: List[Dict[str, Any]] = {models_literal}


# ============================================================================
# Constants
# ============================================================================

POSITION_LIMIT = 10
BASE_QTY = 3
MID_BUFFER_LEN = 520
MPDEV_BUFFER_LEN = 8
RET1_BUFFER_LEN = 4
TRADEFLOW_BUFFER_LEN = 25
WARMUP_TICKS = 60

# Build target -> model index lookup at module load.
TARGETS_BY_SYMBOL: Dict[str, int] = {{}}
for _i, _m in enumerate(MODELS):
    if _m["kind"] == "simple_signal":
        TARGETS_BY_SYMBOL[_m["product"]] = _i
    else:
        # ML kind would trade the whole family; not currently produced but supported.
        for _p in _m.get("family_products", []):
            TARGETS_BY_SYMBOL[_p] = _i

ALL_PRODUCTS: List[str] = sorted(TARGETS_BY_SYMBOL.keys())


# ============================================================================
# Feature helpers
# ============================================================================

def _ob_imbalances(od: OrderDepth) -> Tuple[float, float]:
    bids = od.buy_orders
    asks = od.sell_orders
    if not bids or not asks:
        return 0.0, 0.0
    bid_levels = sorted(bids.items(), key=lambda kv: -kv[0])[:3]
    ask_levels = sorted(asks.items(), key=lambda kv: kv[0])[:3]
    b1 = float(bid_levels[0][1]) if bid_levels else 0.0
    a1 = float(-ask_levels[0][1]) if ask_levels else 0.0
    bT = sum(float(v) for _, v in bid_levels)
    aT = sum(float(-v) for _, v in ask_levels)
    obi_l1 = (b1 - a1) / (b1 + a1) if (b1 + a1) > 0 else 0.0
    obi_l3 = (bT - aT) / (bT + aT) if (bT + aT) > 0 else 0.0
    return obi_l1, obi_l3


def _microprice_dev(od: OrderDepth, mid: float) -> float:
    bids = od.buy_orders
    asks = od.sell_orders
    if not bids or not asks:
        return 0.0
    best_bid = max(bids.keys())
    best_ask = min(asks.keys())
    b1 = float(bids[best_bid])
    a1 = float(-asks[best_ask])
    if (b1 + a1) <= 0:
        return 0.0
    return (best_bid * a1 + best_ask * b1) / (b1 + a1) - mid


def _running_std(seq: List[float]) -> float:
    n = len(seq)
    if n < 2:
        return 0.0
    mu = sum(seq) / n
    var = sum((x - mu) ** 2 for x in seq) / (n - 1)
    return var ** 0.5


def compute_feature(name: str, sym: str, od: OrderDepth, bid: int, ask: int,
                    mid: float, mids: List[float], r1seq: List[float],
                    mpdev_seq: List[float], flow: List[float]) -> float:
    if name == "obi_l1":
        return _ob_imbalances(od)[0]
    if name == "obi_l3":
        return _ob_imbalances(od)[1]
    if name == "microprice_dev":
        return _microprice_dev(od, mid)
    if name == "spread_bps":
        return (1e4 * (ask - bid) / mid) if mid > 0 else 0.0
    if name == "neg_spread":
        return -float(ask - bid)
    if name == "ret_10" or name == "momentum_10":
        return (mid - mids[-11]) if len(mids) >= 11 else 0.0
    if name == "ret_1_lag1":
        return r1seq[-2] if len(r1seq) >= 2 else 0.0
    if name == "std_50":
        return _running_std(mids[-50:]) if len(mids) >= 10 else 0.0
    if name == "std_500":
        return _running_std(mids[-500:]) if len(mids) >= 50 else 0.0
    if name == "microprice_dev_lag5":
        return mpdev_seq[-6] if len(mpdev_seq) >= 6 else 0.0
    if name == "signed_flow_20" or name == "trade_imbalance":
        return float(sum(flow[-20:])) if flow else 0.0
    if name == "neg_zscore_mid_50" or name == "neg_zscore_vwap_50":
        if len(mids) < 50:
            return 0.0
        recent = mids[-50:]
        mu = sum(recent) / 50
        sd = _running_std(recent)
        return (-(mid - mu) / sd) if sd > 0 else 0.0
    return 0.0


def predict_edge(model: Dict[str, Any], sym: str, od: OrderDepth, bid: int,
                 ask: int, mid: float, mids: List[float], r1seq: List[float],
                 mpdev_seq: List[float], flow: List[float]) -> float:
    feats = list(model.get("features") or [model.get("signal")])
    mus = list(model.get("feature_means", [0.0] * len(feats)))
    sds = list(model.get("feature_stds", [1.0] * len(feats)))
    coefs = list(model.get("coefs", [0.0] * len(feats)))
    intercept = float(model.get("intercept", 0.0))
    edge = intercept
    for i, fname in enumerate(feats):
        x = compute_feature(fname, sym, od, bid, ask, mid, mids, r1seq, mpdev_seq, flow)
        mu = mus[i] if i < len(mus) else 0.0
        sd = sds[i] if i < len(sds) and sds[i] != 0 else 1.0
        edge += coefs[i] * (x - mu) / sd
    return edge


# ============================================================================
# Trader
# ============================================================================


class Trader:
    def run(self, state: TradingState) -> Tuple[Dict[Symbol, List[Order]], int, str]:
        result: Dict[Symbol, List[Order]] = {{}}
        conversions = 0
        td = json.loads(state.traderData) if state.traderData else {{}}

        mids_hist: Dict[str, List[float]] = td.get("mids", {{}})
        mpdev_hist: Dict[str, List[float]] = td.get("mpdev", {{}})
        ret1_hist: Dict[str, List[float]] = td.get("ret1", {{}})
        flow_hist: Dict[str, List[float]] = td.get("flow", {{}})

        bb: Dict[str, int] = {{}}
        ba: Dict[str, int] = {{}}
        mids_now: Dict[str, float] = {{}}

        for sym in ALL_PRODUCTS:
            if sym not in state.order_depths:
                continue
            od = state.order_depths[sym]
            if not od.buy_orders or not od.sell_orders:
                continue
            bb[sym] = max(od.buy_orders.keys())
            ba[sym] = min(od.sell_orders.keys())
            mids_now[sym] = (bb[sym] + ba[sym]) / 2.0

        # Update buffers BEFORE computing features so the current tick's mid
        # is included in the rolling history (matches research_lib semantics).
        for sym, mid in mids_now.items():
            hist = mids_hist.get(sym, [])
            ret_1 = (mid - hist[-1]) if hist else 0.0
            hist.append(mid)
            if len(hist) > MID_BUFFER_LEN:
                hist = hist[-MID_BUFFER_LEN:]
            mids_hist[sym] = hist

            r1seq = ret1_hist.get(sym, [])
            r1seq.append(ret_1)
            if len(r1seq) > RET1_BUFFER_LEN:
                r1seq = r1seq[-RET1_BUFFER_LEN:]
            ret1_hist[sym] = r1seq

            mp_dev_now = _microprice_dev(state.order_depths[sym], mid)
            mp_seq = mpdev_hist.get(sym, [])
            mp_seq.append(mp_dev_now)
            if len(mp_seq) > MPDEV_BUFFER_LEN:
                mp_seq = mp_seq[-MPDEV_BUFFER_LEN:]
            mpdev_hist[sym] = mp_seq

            flow = flow_hist.get(sym, [])
            mkt = state.market_trades.get(sym, [])
            new_pts = 0.0
            for t in mkt:
                try:
                    p = float(t.price)
                    q = float(t.quantity)
                except Exception:
                    continue
                sgn = 1.0 if p > mid else (-1.0 if p < mid else 0.0)
                new_pts += sgn * q
            flow.append(new_pts)
            if len(flow) > TRADEFLOW_BUFFER_LEN:
                flow = flow[-TRADEFLOW_BUFFER_LEN:]
            flow_hist[sym] = flow

        for sym, model_idx in TARGETS_BY_SYMBOL.items():
            if sym not in mids_now:
                continue
            mids_local = mids_hist.get(sym, [])
            if len(mids_local) < WARMUP_TICKS:
                continue
            model = MODELS[model_idx]
            edge_raw = predict_edge(
                model, sym, state.order_depths[sym], bb[sym], ba[sym], mids_now[sym],
                mids_local, ret1_hist.get(sym, []),
                mpdev_hist.get(sym, []), flow_hist.get(sym, []),
            )
            edge = edge_raw * float(model.get("live_haircut", 0.3))
            buf = float(model.get("entry_buffer", 0.0))
            spread = float(ba[sym] - bb[sym])
            threshold = 0.5 * spread + buf

            pos = state.position.get(sym, 0)
            orders: List[Order] = []
            if edge > threshold and pos < POSITION_LIMIT:
                qty = min(BASE_QTY, POSITION_LIMIT - pos)
                if qty > 0:
                    orders.append(Order(sym, ba[sym], +qty))
            elif edge < -threshold and pos > -POSITION_LIMIT:
                qty = min(BASE_QTY, POSITION_LIMIT + pos)
                if qty > 0:
                    orders.append(Order(sym, bb[sym], -qty))
            if orders:
                result[sym] = orders

        td["mids"] = mids_hist
        td["mpdev"] = mpdev_hist
        td["ret1"] = ret1_hist
        td["flow"] = flow_hist
        s = json.dumps(td)
        logger.flush(state, result, conversions, s)
        return result, conversions, s
'''


def emit_combined(artifact_paths: list[Path], out_path: Path) -> Path:
    models = [json.loads(p.read_text(encoding="utf-8")) for p in artifact_paths]
    # Disjoint-legs guard: each symbol owned by exactly one model.
    targets: dict[str, str] = {}
    for m in models:
        if m["kind"] == "simple_signal":
            syms = [m["product"]]
        else:
            syms = list(rl.FAMILIES.get(m["family"], []))
        for s in syms:
            if s in targets:
                raise ValueError(f"symbol {s!r} would be owned by both "
                                 f"{targets[s]!r} and {m['family']!r} — refuse to combine")
            targets[s] = m["family"]

    sources = ", ".join(sorted(p.name for p in artifact_paths))
    targets_list = "\n".join(f"  - {s}  ({fam})" for s, fam in sorted(targets.items()))
    models_literal = pprint.pformat(models, indent=2, width=120, sort_dicts=False)
    rendered = _TEMPLATE.format(
        n_models=len(models),
        sources=sources,
        targets_list=targets_list,
        models_literal=models_literal,
    )
    out_path.write_text(rendered, encoding="utf-8")
    return out_path


def main() -> int:
    ap = argparse.ArgumentParser(description="Combine model artifacts into one trader.")
    ap.add_argument("artifacts", nargs="+", type=Path)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    out = emit_combined(args.artifacts, args.out)
    print(f"wrote {out}  ({len(args.artifacts)} models)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
